from src.clock_angle import clock_angle
from src.add_number import add_func
from src.power_func import pow_func
from src.swap_number import swap
from src.condition_print import condition_print
from src.max_min import max_min_number
from src.cube_sum import get_cube
from src.multiply import multiply
from src.is_even import is_even
from src.square import square
from src.oneline import one_line_set_two
from src.minimum import minimum
from src.division import divide
from src.ternary import ternary
